### ISSUE TITLE
Error when configuring multiple options

### ISSUE THREAD

**Issue by sonofjavascript** [dukeluo/eslint-plugin-check-file#52]
**Describe the bug**
I'm encountering an error when trying to configure any of the rules with multiple options. Here is my .eslintrc.js configuration:

```
...
plugins: ['check-file'],
'check-file/folder-naming-convention': [
  'error',
   {
     '*': 'KEBAB_CASE',
   },
   {
     ignoreMiddleExtensions: true,
   },
 ]
```

When I run ESLint, it throws the following error:

```
Error: Key "rules": Key "check-file/folder-naming-convention":
        Value [{"*":"KEBAB_CASE"},{"ignoreMiddleExtensions":true}] should NOT have more than 1 items.

    at RuleValidator.validate (/path/to/node_modules/eslint/lib/config/rule-validator.js:170:27)
    at new Config (/path/to/node_modules/eslint/lib/config/config.js:228:27)
    at [finalizeConfig] (/path/to/node_modules/eslint/lib/config/flat-config-array.js:216:16)
    at FlatConfigArray.getConfigWithStatus (/path/to/node_modules/@eslint/config-array/dist/cjs/index.cjs:1178:55)
    at FlatConfigArray.getConfig (/path/to/node_modules/@eslint/config-array/dist/cjs/index.cjs:1196:15)
    at entryFilter (/path/to/node_modules/eslint/lib/eslint/eslint-helpers.js:282:40)
    at async NodeHfs.<anonymous> (/path/to/node_modules/@humanfs/core/src/hfs.js:574:24)
```

**Plugin configuration**
Your configuration of this plugin.

**Additional context**
I am using eslint flat config with 9.15.0 version.

**Comment by dukeluo** [comment]
@sonofjavascript could you try this:
```js
     "check-file/folder-naming-convention": [
        "error",
        {
          "**/": "KEBAB_CASE",
        },
      ],
```
